### PR TITLE
Converting essays for module 3 to pdf and serve them from the page

### PR DESCRIPTION
**Pull request by ercchy**
- all the essays were converted to pdf (docx formats deleted)
- listed in a new file in _data folder
- displayed in Module 3: Readings file within for loop

### CODE REVIEW

**Comment by dirkcuys** [comment]
Hey Erika. Looks good, PDF is way better than docx or pages!

Be carefull when using _data. It is a good idea to use it to avoid duplicate data in different places, but it is a somewhat advanced feature compared to the rest of Jekyll.

In this instance it saves you from repeating some HTML, but if someone wants to correct a title for one of the essays, they would need to understand how _data works to find the right file to edit.

**Comment by ercchy** [comment]
I agree, with the _data usage, however this was specific ask from VMG.

**Comment by dirkcuys** [comment]
Did Vanessa specifically ask to put it in _data?

**Comment by ercchy** [comment]
No, but she wanted to have it like on p2pu webpage

**Comment by dirkcuys** [comment]
It's something to keep in mind when using Jekyll. One of the strongest arguments for using Jekyll is its simplicity. If we get too fancy we negate that reason.

You can merge this whenver you like - the only reason I didn't merge it straight aways was because I assumed you wanted some feedback from Vanessa.

**Comment by ercchy** [comment]
Yes, I wanted to wait for her to be ready. I have sent her an email about
it this morning....

Erikaツ

**Pull request merged**
